# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ce6b6821b749f4c1e001301d90ae1b13e0fbfd98d60dba3f6e19008f5b192449b45ff086ed1e0bf8e988e74b3ef90344c9dd8181407eebf6e82235ee55db3e8

test:
  secret_key_base: e73d37f9b974dc06ea85a3d06e27d847b6eee98a16560aca67c2d31ea2fa6e48c2823204cba7975b15e423513d077f1aa45e65648e2f919046619e44c268b422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
